version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/workspace
    ports:
      - 5000:5000

  
